apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "generic-app.fullname" . }}
spec:
  data:
    - secretKey: .env
      remoteRef:
        key: {{ include "generic-app.fullname" . }}
        property: .env
  # manually refresh or via a different pipeline/process to minimize api calls and cost
  refreshInterval: 0h
  secretStoreRef:
    kind: {{ .Values.secretStore.kind }}
    name: {{ .Values.secretStore.name }}
