apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: k8s-secrets-vault-ns
spec:
  provider:
    # this kubernetes is a simulation of how aws-secrets-manager would be configured
    kubernetes:
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets
      # with this, the store is able to pull only from `vault` namespace
      remoteNamespace: vault
      server:
        caProvider:
          type: ConfigMap
          namespace: external-secrets
          name: kube-root-ca.crt
          key: ca.crt
