name: katib ci build & push & deploy
run-name: katib ci build & push & deploy for ${{ github.ref_name }}

on:
  push:
    tags:
      - "katib-v*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the Docker image (e.g., v1.0 or git SHA)"
        required: true
        type: string

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
    defaults:
      run:
        working-directory: ./katib
    steps:
      - uses: actions/checkout@v6
      - name: Extract version from reference
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ inputs.tag }}"
          else
            VERSION=$(echo "${{ github.ref_name }}" | sed 's/^katib-//')
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        # NOTE: we can harden this by pinning to the commit SHA (5e57cd118135c172c3672efd75eb46360885c0ef)
        # to prevent supply chain attacks
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./katib
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/katib:${{ steps.version.outputs.VERSION }},${{ vars.DOCKERHUB_USERNAME }}/katib:latest
          # remote layer caching to speed up builds
          # on aws we would use a specific tag in the ecr repo for this like `buildcache`
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    # required to allow pushing commits back to the repo
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - uses: actions/checkout@v6

      - name: Set image tag in values.yaml
        env:
          VERSION: ${{ needs.docker-build-push.outputs.version }}
        run: |
          echo "version is $VERSION"
          yq e ".deployment.image.tag = \"$VERSION\"" -i "devops/helm/apps/katib/values.yaml"

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add devops/helm/apps/katib/values.yaml
          git commit -m "cd: update katib image tag to ${{ needs.docker-build-push.outputs.version }}"
          git push
